[2023-03-03T15:27:25.736+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_nexrad_data manual__2023-03-03T15:27:10.977441+00:00 [queued]>
[2023-03-03T15:27:25.999+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_nexrad_data manual__2023-03-03T15:27:10.977441+00:00 [queued]>
[2023-03-03T15:27:26.002+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T15:27:26.003+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-03T15:27:26.005+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T15:27:26.060+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_nexrad_data> on 2023-03-03 15:27:10.977441+00:00
[2023-03-03T15:27:26.219+0000] {standard_task_runner.py:55} INFO - Started process 285 to run task
[2023-03-03T15:27:27.566+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_nexrad_data', 'manual__2023-03-03T15:27:10.977441+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmpwrp1edp0']
[2023-03-03T15:27:28.420+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask scrape_nexrad_data
[2023-03-03T15:27:36.534+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_nexrad_data manual__2023-03-03T15:27:10.977441+00:00 [running]> on host 63718f10a2c9
[2023-03-03T15:27:36.911+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_nexrad_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T15:27:10.977441+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T15:27:10.977441+00:00
[2023-03-03T15:27:36.931+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 110, in NEXRAD_scrap_load
    result = s3.list_objects(Bucket=nexrad_bucket, Prefix=prefix, Delimiter='/')
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2023-03-03T15:27:36.971+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_nexrad_data, execution_date=20230303T152710, start_date=20230303T152725, end_date=20230303T152736
[2023-03-03T15:27:37.004+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 11 for task scrape_nexrad_data (Unable to locate credentials; 285)
[2023-03-03T15:27:37.098+0000] {local_task_job.py:208} INFO - Task exited with return code 1
