[2023-03-02T19:05:57.750+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-02T19:05:54.685462+00:00 [queued]>
[2023-03-02T19:05:57.759+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-02T19:05:54.685462+00:00 [queued]>
[2023-03-02T19:05:57.760+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T19:05:57.768+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T19:05:57.768+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T19:05:57.786+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): fetch_nexrad_stations> on 2023-03-02 19:05:54.685462+00:00
[2023-03-02T19:05:57.808+0000] {standard_task_runner.py:55} INFO - Started process 2501 to run task
[2023-03-02T19:05:57.837+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'fetch_nexrad_stations', 'manual__2023-03-02T19:05:54.685462+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmpnhtij__p']
[2023-03-02T19:05:57.847+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask fetch_nexrad_stations
[2023-03-02T19:05:57.981+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.fetch_nexrad_stations manual__2023-03-02T19:05:54.685462+00:00 [running]> on host f6e174e28dc0
[2023-03-02T19:05:58.108+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=fetch_nexrad_stations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T19:05:54.685462+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T19:05:54.685462+00:00
[2023-03-02T19:05:58.233+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 168, in nexrad_stations
    df = pd.read_csv("../working_dir/data/nexrad-stations.txt", colspecs=cols, skiprows=[1])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
TypeError: read_csv() got an unexpected keyword argument 'colspecs'
[2023-03-02T19:05:58.260+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=fetch_nexrad_stations, execution_date=20230302T190554, start_date=20230302T190557, end_date=20230302T190558
[2023-03-02T19:05:58.275+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task fetch_nexrad_stations (read_csv() got an unexpected keyword argument 'colspecs'; 2501)
[2023-03-02T19:05:58.340+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T19:05:58.386+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
